spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/gestionale
    username: we
    password: we
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        format-sql: true

server:
  port: 8081